// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodP9sOVOENTZBu6JKGPMub1g2Q0baqec',
    appId: '1:373637410895:web:8e6a200b71fc494bf8ba3a',
    messagingSenderId: '373637410895',
    projectId: 'it-materials-point',
    authDomain: 'it-materials-point.firebaseapp.com',
    storageBucket: 'it-materials-point.appspot.com',
    measurementId: 'G-RL52XJFFCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9vOyJCxtbIz9n9iDfnHUmccnmxNOHMvU',
    appId: '1:373637410895:android:2f21cc5d1a416c4ff8ba3a',
    messagingSenderId: '373637410895',
    projectId: 'it-materials-point',
    storageBucket: 'it-materials-point.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HsxSeQwMPZZWNmul6uflExxGhu4T8AQ',
    appId: '1:373637410895:ios:525159265c00ed2ef8ba3a',
    messagingSenderId: '373637410895',
    projectId: 'it-materials-point',
    storageBucket: 'it-materials-point.appspot.com',
    iosBundleId: 'com.example.itmaterialspoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HsxSeQwMPZZWNmul6uflExxGhu4T8AQ',
    appId: '1:373637410895:ios:525159265c00ed2ef8ba3a',
    messagingSenderId: '373637410895',
    projectId: 'it-materials-point',
    storageBucket: 'it-materials-point.appspot.com',
    iosBundleId: 'com.example.itmaterialspoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodP9sOVOENTZBu6JKGPMub1g2Q0baqec',
    appId: '1:373637410895:web:a0b29b35896213c9f8ba3a',
    messagingSenderId: '373637410895',
    projectId: 'it-materials-point',
    authDomain: 'it-materials-point.firebaseapp.com',
    storageBucket: 'it-materials-point.appspot.com',
    measurementId: 'G-PFT6LXJE1M',
  );
}
